### ISSUE TITLE
The character doest move

### ISSUE THREAD

**Issue by deiangi** [WorldGrower/WorldGrower#2]
The game starts it displays the main character, however the screen the character doesn't move with the arrows. I do hear the steps though. If I click esc the menu shows up but the game disappears and the desktop shows.

I ran both from the binary distro and from the source code to the same effect.
No exceptions .. 

Any idea?

**Comment by WorldGrower** [comment]
Thanks for the feedback, I have some ideas:
- if you left-click on an open space, does it show the go to menu (green boot icon)? And are you able to move like that?
- if you press tab, are you able to move using the arrow keys?

And it would be great if you could answer one more question, on what operating system are you running the game?

**Comment by deiangi** [comment]
I tried on a different machine - this time worked just fine. btw a lot of work you've put and many nice ideas. good job.

**Comment by WorldGrower** [comment]
Good to hear it worked on a different machine.
Thanks for the compliments.
