### ISSUE TITLE
Factory Methods

### ISSUE THREAD

**Issue by chen-robert** [WorldGrower/WorldGrower#5]
From a preliminary glance, it seems that most Factory methods could be made static. 

This would remove the need to create instances of the factories.

**Comment by WorldGrower** [comment]
Hi,

thanks for the comment.
could you give an example of a factory method that could be made static?

**Comment by chen-robert** [comment]
TaxAndWagesCalculator has neither a constructor nor any fields meaning that it does the same thing for all instances of TaxAndWagesCalculator and could be static.

**Comment by WorldGrower** [comment]
Yes, you're correct.
I changed the methods to be static.
